### ISSUE TITLE
Can I use more replica nodes to scale?

### ISSUE THREAD

**Issue by xpdavid** [DistributedTeam/MongoDB#19]
http://www.askasya.com/post/canreplicashelpscaling/

Do not use secondary reads to scale overall read throughput. See: Can I use more replica nodes to scale for an overview of read scaling. For information about secondary reads, see: Read Preference.

Will more servers help you handle same reads faster?

I think the answer for simple operational reads is obviously no. If a read takes 10μs then it’s not likely to take 1/5th of that just because there are five servers - this is a single unit of work. That’s the actual duration of the read.

Will more servers help you handle more reads?

Intuitively, it feels like the answer should be “yes” - but that would only be the case if the reads somehow interfered with each other on the single node. If they are reading the same “hot” data then they can be working in parallel up to the limit of your CPUs. So in real life, the answer to whether all your replica nodes together can handle more reads than just your primary is maybe yes and maybe no. Usually no. It all depends on why your single primary cannot handle all of the reads by itself.

**Comment by leshweyeewin** [comment]
If Read Preference is set to Primary(Default), adding more replica nodes does not help for scaling, since all the read operations are routed to primary node.
However, readings from secondary nodes could be stale, so not advised to be used.
Adding more replica nodes helps for high availability though. During failover, one of the secondary nodes with highest priority gets elected as new primary node, and continues to serve the read and write operations.
Although not for Java but Python, http://api.mongodb.com/python/current/examples/high_availability.html has a clear explanation of connection to replica set, and failover handling.
During failover, exception will be raised for unavailable primary node, so need to retry the operation until the driver discovers the new primary node.
