### ISSUE TITLE
Explore the options/technique to improve performance in mongodb java driver

### ISSUE THREAD

**Issue by xpdavid** [DistributedTeam/MongoDB#24]
http://mongodb.github.io/mongo-java-driver/

We will definitely use projections to retrieve partial data instead of full document.

**Comment by xpdavid** [comment]
Related to #10

**Comment by leshweyeewin** [comment]
In some cases where many fields need to be updated in a document, it may be more efficient to replace the document. The replacement document can have different fields from the original document. In the replacement document, the _id field can be omitted since the _id field is immutable; however, if the _id field needs to be included, must specify the same value for the _id field as the original document.

**Comment by leshweyeewin** [comment]
Updates.currentDate to modify a field to the current date. If the field does not exist, the operator adds the field to the document.

**Comment by leshweyeewin** [comment]
The find().first() construct is useful for queries that should only match a single document.

**Comment by leshweyeewin** [comment]
Use projections, filtering, limiting the no. of query results whenever applicable to return only necessary data to Reduce Network Demand.

**Comment by leshweyeewin** [comment]
MongoClient is designed for multi-threaded calls and has a connection pool internally (default pool size in Java is 100). Hence for most use cases you will need just one instance of MongoClient. Using multiple MongoClient instances may lead to too many open connections in MongoDB.

**Comment by leshweyeewin** [comment]
If you pass a List of Mongo addresses the driver switches to the replica set mode. In this case it automatically discovers the primary in the replica set. However, if you only pass one address and this one is not available on start-up the driver doesn’t start.
new MongoClient(asList(serverAddress1, serverAddress2))
Best Practices:
Always define several members of the replica set. So it’s not so bad if one is not available on start-up. The driver still finds the replica set and the primary.
Be aware of the MongoExceptions which will be thrown in case of a failure (e.g. failover, network errors, unique key constraints). Catch the exception if necessary (e.g. when you want to continue with another element instead of aborting completely).
