### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by xpdavid** [DistributedTeam/MongoDB#4]
In MongoDB a replica set is made up of a **primary** node and a number of secondary or **arbiter** nodes.

In replica set terms, a primary is **the source of truth** at a given moment for your replica set.
_It is the only node in the set to which data can be directly written to via your application and from which all other nodes ultimately replicate this data._

A secondary member is a data-carrying nonprimary member, which can (barring a few exceptions) theoretically become a primary.

![image](https://user-images.githubusercontent.com/13977235/31853762-d8099992-b6c0-11e7-8520-597fafb83544.png)

**Comment by xpdavid** [comment]
$ mkdir -p /db/active1/data
$ mongod --dbpath /db/active1/data --port 27021 --replSet testset

> rs.initiate()

**Comment by elijahsk** [comment]
Replication provides high availability of data as the automatic failover process allows secondary member to be elected to be the primary member when the primary member is done.

However, as the secondary members have to duplicate the Oplog of the primary member and apply the changes afterwards. There may be chances of reading stale data from the secondary members due to the asynchronous nature of replication. 

Furthermore, if a secondary member is far too behind the progress of the primary member, there might be the case that the Oplog of the primary member is overwritten before it is duplicated and applied to the secondary member. In this case, a re-syncing is necessary but requires more CPU.

Thus, it is personally suggested that:
1. Perform reads on secondary member only on tables that do not incur frequent changes;
2. Increase the size of Oplog to prevent situations mentioned above.(https://docs.mongodb.com/manual/tutorial/change-oplog-size/);
3. The need for Priority 0 / Hidden / Delayed replica set member has not been seen.
